algoritmo "Exercicio17"
// Função :
// Autor :
// Data : 06/10/2024
// Seção de Declarações 

var
    celsius, fahrenheit: real
inicio
    // Entrada: temperatura em Celsius
    escreva("Digite a temperatura em graus Celsius: ")
    leia(celsius)

    // Cálculo: conversão para Fahrenheit
    fahrenheit <- (celsius * 9 / 5) + 32

    // Saída: temperatura em Fahrenheit
    escreval("A temperatura em Fahrenheit é: ", fahrenheit:0:2)

fimalgoritmo



